# Generated by Django 3.1 on 2020-08-22 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('preco_venda', models.FloatField(blank=True, null=True, verbose_name='Preço de Venda')),
                ('bloqueado', models.BooleanField(default=False, verbose_name='Bloqueado')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
            ],
            options={
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimento', models.DateField(auto_now_add=True, verbose_name='Data do Movimento')),
                ('tipo_movimento', models.IntegerField(choices=[(1, 'Saída'), (2, 'Entrada')], verbose_name='Tipo de Movimento')),
                ('quantidade', models.FloatField(verbose_name='Quantidade')),
                ('preco_venda', models.FloatField(blank=True, null=True, verbose_name='Preço de Venda')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observação')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque.produto', verbose_name='Produto')),
            ],
        ),
    ]
