# Generated by Django 3.1 on 2020-09-16 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_auto_20200916_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='bloqueado',
            field=models.BooleanField(default=False, editable=False, verbose_name='Bloqueado'),
        ),
    ]
