# Generated by Django 3.1 on 2020-09-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_auto_20200916_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentoestoque',
            name='observacao',
            field=models.TextField(blank=True, default=0, verbose_name='Observação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='preco_venda',
            field=models.FloatField(blank=True, default=0, verbose_name='Preço de Venda'),
            preserve_default=False,
        ),
    ]
