# Generated by Django 3.1 on 2020-09-17 21:00

from django.db import migrations, models
import django.utils.timezone
import utilitario.validadores


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_auto_20200916_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentoestoque',
            name='preco_venda',
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='data_registro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data do Registro do Movimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentoestoque',
            name='valor',
            field=models.FloatField(blank=True, default=0, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='data_movimento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data do Movimento'),
        ),
        migrations.AlterField(
            model_name='movimentoestoque',
            name='observacao',
            field=models.TextField(blank=True, default='', verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='observacao',
            field=models.TextField(blank=True, default='', verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_venda',
            field=models.FloatField(blank=True, validators=[utilitario.validadores.Validador.valida_preco_venda_produto], verbose_name='Preço de Venda'),
        ),
    ]
