# Generated by Django 3.1 on 2020-08-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('nome', models.CharField(max_length=150)),
                ('cpf_cnpj', models.CharField(max_length=14)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('cliente', models.BooleanField()),
                ('fornecedor', models.BooleanField()),
            ],
            options={
                'db_table': 'entidade',
            },
        ),
    ]
