# Generated by Django 3.1 on 2020-08-21 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entidade', '0002_auto_20200821_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEndereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
            options={
                'db_table': 'tipo_endereco',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=150, verbose_name='Logradouro')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(max_length=50, verbose_name='Complemento')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=50, verbose_name='Estado')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
                ('pais', models.CharField(max_length=25, verbose_name='País')),
                ('observacao', models.TextField(verbose_name='Observação')),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidade.entidade', verbose_name='Entidade')),
                ('tipo_endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entidade.tipoendereco', verbose_name='Tipo de Endereço')),
            ],
            options={
                'db_table': 'endereco',
            },
        ),
    ]
