# Generated by Django 3.1 on 2020-08-28 23:07

from django.db import migrations, models
import utilitario.validadores


class Migration(migrations.Migration):

    dependencies = [
        ('entidade', '0004_auto_20200828_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='cpf_cnpj',
            field=models.CharField(max_length=14, validators=[utilitario.validadores.Validador.valida_cpf_cnpj_api], verbose_name='CPF/CNPJ'),
        ),
    ]
