# Generated by Django 3.1 on 2020-08-29 00:41

from django.db import migrations, models
import django.db.models.deletion
import utilitario.validadores


class Migration(migrations.Migration):

    dependencies = [
        ('entidade', '0005_auto_20200828_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entidade',
            name='cpf_cnpj',
            field=models.CharField(max_length=14, validators=[utilitario.validadores.Validador.valida_cpf_cnpj_api], verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='ramal',
            field=models.CharField(blank=True, max_length=5, verbose_name='Ramal'),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='tipo_telefone',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='entidade.tipotelefone', verbose_name='Tipo de Telefone'),
        ),
    ]
