# Generated by Django 3.1 on 2020-08-29 13:18

from django.db import migrations, models
import django.db.models.deletion
import utilitario.validadores


class Migration(migrations.Migration):

    dependencies = [
        ('entidade', '0007_auto_20200828_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='complemento',
            field=models.CharField(blank=True, max_length=50, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='observacao',
            field=models.TextField(blank=True, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='tipo_endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entidade.tipoendereco', verbose_name='Tipo de Endereço'),
        ),
        migrations.AlterField(
            model_name='entidade',
            name='cpf_cnpj',
            field=models.CharField(max_length=14, validators=[utilitario.validadores.Validador.valida_cpf_cnpj_api], verbose_name='CPF/CNPJ'),
        ),
    ]
