# Generated by Django 3.1 on 2020-08-24 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=6, verbose_name='Número')),
                ('data_emissao', models.DateField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('status', models.IntegerField(choices=[(1, 'Cadastrado'), (2, 'Faturado'), (3, 'Cancelado')], default=1, editable=False, verbose_name='Status de Emissão')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(verbose_name='Quantidade')),
                ('valor_unitario', models.FloatField(verbose_name='Valor Unitário')),
                ('desconto_percentual', models.FloatField(verbose_name='Desconto %')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.pedido', verbose_name='Pedido')),
            ],
            options={
                'db_table': 'item_pedido',
            },
        ),
    ]
