# Generated by Django 3.1 on 2020-08-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_auto_20200824_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='desconto_percentual',
            field=models.FloatField(blank=True, null=True, verbose_name='Desconto %'),
        ),
    ]
