# Generated by Django 3.1 on 2020-08-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_auto_20200824_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.IntegerField(choices=[(1, 'Cadastrado'), (2, 'Faturado'), (3, 'Cancelado')], default=1, editable=False, verbose_name='Status do Pedido'),
        ),
    ]
