# Generated by Django 3.1 on 2020-08-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0009_auto_20200829_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='desconto_percentual',
            field=models.FloatField(blank=True, default=0, verbose_name='Desconto %'),
        ),
    ]
