# Generated by Django 3.1 on 2020-08-25 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('data_emissao', models.DateField(auto_now_add=True, verbose_name='Data de Emissão')),
                ('status', models.IntegerField(choices=[(1, 'Cadastrada'), (2, 'Emitida'), (3, 'Cancelada')], default=1, editable=False, verbose_name='Status da Nota Fiscal')),
            ],
            options={
                'db_table': 'notafiscal',
            },
        ),
        migrations.CreateModel(
            name='ItemNotaFiscal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(verbose_name='Quantidade')),
                ('valor_unitario', models.FloatField(verbose_name='Valor Unitário')),
                ('desconto_percentual', models.FloatField(blank=True, null=True, verbose_name='Desconto %')),
                ('notafiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notafiscal.notafiscal', verbose_name='Nota Fiscal')),
            ],
            options={
                'db_table': 'item_notafiscal',
            },
        ),
    ]
